// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALrND8jlEg0dBwW64sLk4zbnffcd-Tk6c',
    appId: '1:441375765301:android:a0e7eedd1e7ac850d2d27c',
    messagingSenderId: '441375765301',
    projectId: 'pet-keeper-6f5ac',
    storageBucket: 'pet-keeper-6f5ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfTlcaEuhKCGqBt9mdsEj6mQw8b_OSndk',
    appId: '1:441375765301:ios:02a9a337fe5fb822d2d27c',
    messagingSenderId: '441375765301',
    projectId: 'pet-keeper-6f5ac',
    storageBucket: 'pet-keeper-6f5ac.firebasestorage.app',
    iosClientId: '441375765301-4dq5uammo7ltbotisavh3df71ipjmqhn.apps.googleusercontent.com',
    iosBundleId: 'com.example.petKeeperLite',
  );
}
